### ISSUE TITLE
docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /usr/local/lib/node_modules/@tuyapi/cli/node_modules/tmp/LICENSE: invalid argument.

### ISSUE THREAD

**Issue by aldobranti** [shtrom/tuyapi-docker#1]
I run this command 
`docker run --rm -it omehani/tuya-cli wizard`
in the linux container on my Chromebox

to receive error
`docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /usr/local/lib/node_modules/@tuyapi/cli/node_modules/tmp/LICENSE: invalid argument.`

[https://github.com/moby/moby/issues/43576](https://github.com/moby/moby/issues/43576) suggests that this might be subuid/subgid problem

PLEASE reveal what uid and gid are used to build and so allow me to edit /etc/subuid /etc/subgid locally

**Comment by shtrom** [comment]
It's all in the Dockerfile. This image is built using node:latest as the base, and doesn't do any uid handing itself.

It seems the error happens during a pull, but you haven't included that output. Can you tell which layer causes the issue?

It seems like the subuid config files are not in the container image, but on your host, so I'd take a punt and put larger(?) values in there and retry.

Otherwise, it might be worth checking how the node:latest container is built, and/or try to rebuild the tuya-cli image yourself.
-- 
Olivier Mehani ***@***.***>
Sent from my mobile, please excuse my brevity.

**Comment by aldobranti** [comment]
Thank you Olivier, succeeded in building fresh on chosen architecture. So closing this issue
